### ISSUE TITLE
Feature request: Timeout to first byte

### ISSUE THREAD

**Issue by rtheil-growlink** [jmpmscorp/esp-sdi-12#1]
Curious if there's a way to add a "timeout to first byte" feature that would allow the ability to specify a much lower timeout period on the identify command. Our esp device has 4 SDI-12 ports, and we can connect 10 probes on each port. The problem is that the identification process takes quite some time since the lowest timeout period I can implement is about 320ms. So if there's only 1 probe connected to the controller, it takes 320ms * 40 to attempt to detect all probes, which is over 13 seconds. I recently had an issue where we started using a different device and that device couldn't finish its identify response within 300ms, so I had to bump it up 20ms. We also plan to implement many more SDI-12 devices in the future.

A timeout to first byte would allow the controller to time out before the first byte is received from the probe. Usually SDI-12 devices respond within just a few ms, so if there were a 50ms timeout to first byte, it would only time out if the address byte isn't received within 50ms. It would cut the identification process from 13 seconds, to just 2 seconds (not factoring in the rest of the response from detected SDI-12 devices). I think the standard timeout could still apply in case the first byte is received but the entire response times out.

We have this implemented on our old Particle Photon controllers, and it's a huge time saver. Allows the controller to start up more quickly after a reset, and start getting measurements as soon as possible.

**Comment by jmpmscorp** [comment]
Hi @rtheil-growlink.

Reading your requirements, I think you needn't this feature. Instead of issue "idenfication" command (suppose you meant "aI!" command where 'a' is address), you should issue "acknowledge active" command "a!". When sensor receives "a!" command it must answer with "a<CR><LF>". This answer is, of course, shorter than "aI!" command, If you get "a<CR><LF>" response, you assert that this sensor/address is active. If you need sensor information later, you can issue "aI!" before "a!".

**Comment by rtheil-growlink** [comment]
Hey, that's a great idea. Let me try that out. Thanks, as always!

**Comment by rtheil-growlink** [comment]
Thanks so much for the suggestion! I dropped 10 seconds from the probe detection time!
